
export const documentData = [
    {
        id: '1',
        name: 'Policy_Update.pdf',
        type: 'PDF',
        size: '45KB',
        sender: 'Nur Hafizah',
        date: '2024-11-02',
        transferDate: '2024-12-01',
        department: 'Admin',
        note: 'Policy Update 2024',
    },
    {
        id: '2',
        name: 'Quarterly_Report.docx',
        type: 'Word Document',
        size: '32KB',
        sender: 'JOHN DOE',
        date: '2024-11-01',
        transferDate: '2024-11-30',
        department: 'Admin',
        note: 'The Quarterly Report for the 2024 Session',
    },
    {
        id: '3',
        name: 'Quarterly_Report_Edited.docx',
        type: 'Word Document',
        size: '32KB',
        sender: 'Nur Hafizah',
        date: '2024-12-03',
        transferDate: '2024-11-30',
        department: 'Admin',
        note: 'Unfinished Document, Please Continue',
    },
    {
        id: '4',
        name: 'Test.pdf',
        type: 'PDF',
        size: '32KB',
        sender: 'JOHN DOE',
        date: '2024-11-02',
        transferDate: '2024-11-30',
        department: 'Admin',
    },
    {
        id: '5',
        name: 'Test2.docx',
        type: 'Word Document',
        size: '32KB',
        sender: 'JOHN DOE',
        date: '2024-11-12',
        transferDate: '2024-11-30',
        department: 'Admin',
    },
    {
        id: '6',
        name: 'Quarterly_Report_2024.docx',
        type: 'Word Document',
        size: '32KB',
        sender: 'JOHN DOE',
        date: '2024-11-21',
        transferDate: '2024-11-30',
        department: 'Admin',
    },
    {
        id: '7',
        name: 'Quarterly_Report_Edited.docx',
        type: 'Word Document',
        size: '32KB',
        sender: 'Nur Hafizah',
        date: '2024-11-01',
        transferDate: '2024-11-30',
        department: 'Finance',
    },
    {
        id: '8',
        name: 'Test.pdf',
        type: 'PDF',
        size: '32KB',
        sender: 'JOHN DOE',
        date: '2024-11-01',
        transferDate: '2024-11-30',
        department: 'Human Resources',
    },
    {
        id: '9',
        name: 'Test2.docx',
        type: 'Word Document',
        size: '32KB',
        sender: 'JOHN DOE',
        date: '2024-11-01',
        transferDate: '2024-11-30',
        department: 'Human Resources',
    },
    {
        id: '10',
        name: 'Quarterly_Report_2024.docx',
        type: 'Word Document',
        size: '32KB',
        sender: 'JOHN DOE',
        date: '2024-11-01',
        transferDate: '2024-11-30',
        department: 'Engineering',
    },
    

    // Add more documents as needed
];

