
export const documentData = [
    {
        id: '1',
        name: 'Policy_Update.pdf',
        type: 'PDF',
        size: '45KB',
        uploader: 'Nur Hafizah',
        date: '2024-11-02',
        department: 'Admin',
        notes: '',
    },
    {
        id: '2',
        name: 'Quarterly_Report.docx',
        type: 'Word Document',
        size: '32KB',
        uploader: 'JOHN DOE',
        date: '2024-11-01',
        department: 'Admin',
        notes: '',
    },
    {
        id: '3',
        name: 'Quarterly_Report_Edited.docx',
        type: 'Word Document',
        size: '32KB',
        uploader: 'ATHIRAH SHAZLIN',
        date: '2024-12-03',
        department: 'Admin',
        notes: '',
    },
    {
        id: '4',
        name: 'Test.pdf',
        type: 'PDF',
        size: '32KB',
        uploader: 'ATHIRAH SHAZLIN',
        date: '2024-11-02',
        department: 'Admin',
        notes: '',
    },
    {
        id: '5',
        name: 'Test2.docx',
        type: 'Word Document',
        size: '32KB',
        uploader: 'JOHN DOE',
        date: '2024-11-12',
        department: 'Admin',
        notes: '',
    },
    {
        id: '6',
        name: 'Quarterly_Report_2024.docx',
        type: 'Word Document',
        size: '32KB',
        uploader: 'JOHN DOE',
        date: '2024-11-21',
        department: 'Admin',
    },
    {
        id: '7',
        name: 'Quarterly_Report_Edited.docx',
        type: 'Word Document',
        size: '32KB',
        uploader: 'Nur Hafizah',
        date: '2024-11-01',
        department: 'Finance',
        notes: '',
    },
    {
        id: '8',
        name: 'Test.pdf',
        type: 'PDF',
        size: '32KB',
        uploader: 'JOHN DOE',
        date: '2024-11-01',
        department: 'Human Resources',
        notes: '',
    },
    {
        id: '9',
        name: 'Test2.docx',
        type: 'Word Document',
        size: '32KB',
        uploader: 'JOHN DOE',
        date: '2024-11-01',
        department: 'Human Resources',
        notes: '',
    },
    {
        id: '10',
        name: 'Quarterly_Report_2024.docx',
        type: 'Word Document',
        size: '32KB',
        uploader: 'JOHN DOE',
        date: '2024-11-01',
        department: 'Engineering',
        notes: '',
    },
    {
        id: '11',
        name: 'Document_Testo.docx',
        type: 'Word Document',
        size: '32KB',
        uploader: 'ATHIRAH SHAZLIN',
        date: '2024-12-03',
        department: 'Admin',
        notes: '',
    },

    // Add more documents as needed
];

